- name: Disable overlayfs
  become: true
  ansible.builtin.command: "raspi-config nonint do_overlayfs 1"
  changed_when: true

- name: Reboot after disabling overlayfs
  ansible.builtin.reboot:
    reboot_timeout: 120
  become: true