- name: Enable OverlayFs # https://www.raspberrypi.com/documentation/computers/configuration.html#overlay-file-system-2
  become: true
  ansible.builtin.command: "raspi-config nonint do_overlayfs 0" # 0 turns on, write protects.
  changed_when: true

- name: Reboot to enable overlayfs
  ansible.builtin.reboot:
    reboot_timeout: 120
  become: true
