# Path to the dedicated venv for wigglecam
photobooth_venv: "{{ ansible_env.HOME }}/photobooth-venv"
# Data directory used by the app to store images, logs, and config
photobooth_persistent_data_mnt: "/mnt/data"
